patientRecord/urls.py
# this page was created to add custom patterns as development progress
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('patients/', views.PatientListView.as_view(), name='patients'),
    path('patient/<int:pk>', views.PatientDetailView.as_view(), name='patient-details'),
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('device/<int:pk>', views.DeviceDetailView.as_view(), name='device-detail'),
]

# for create and delete device
urlpatterns += [  
    path('device/create/', views.DeviceCreate.as_view(), name='device_create'),
    path('device/<int:pk>/update/', views.DeviceUpdate.as_view(), name='device_update'),
    path('device/<int:pk>/delete/', views.DeviceDelete.as_view(), name='device_delete'),
]

# for create and delete patient details
urlpatterns += [  
    path('patient/create/', views.PatientCreate.as_view(), name='patient_create'),
    path('patient/<int:pk>/update/', views.PatientUpdate.as_view(), name='patient_update'),
    path('patient/<int:pk>/delete/', views.PatientDelete.as_view(), name='patient_delete'),
]

realdrip/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the patientRecord application 
# add the catalog path to the application
from django.urls import include

urlpatterns += [
    path('patientRecord/', include('patientRecord.urls')),
]

#Add URL maps to redirect the base URL to our application
#change the base url 127.0.0.1:8000 to go directly to the patientRecord app
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/patientRecord/')),
]

# Use static() to add url mapping to serve static files during development (only)
# to serve static files, like css and images during development only
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

patientRecord/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
# Models for type of disease admitted for in the clinic
class Diagnosis(models.Model):

    name = models.CharField(max_length=200, help_text="Enter the diagnosis ailments for (e.g stroke, Venous Thromboembolism,etc)")
# represent the model clearly in the admin dashboard
    def __str__(self):
        return self.name

#Models for patient and their details

class Patient(models.Model):

    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    GENDER_STATUS = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_STATUS, blank=True, default='M', help_text="Male/Female")
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=300)
    summary = models.TextField(max_length=1000, help_text="Enter the brief details about the disease/ reason for admission")
    ClinicID = models.CharField('CLINICID',max_length=13, help_text="Enter the clinic unique ID")
    device = models.ForeignKey('Device', on_delete=models.SET_NULL, null=True)
    diagnosis = models.ManyToManyField(Diagnosis, help_text="Enter the diagnosis type for the patient")

    def __str__(self):

        return self.firstname

    def get_absolute_url(self):

        return reverse('patient-details', args=[str(self.id)])

    def display_diagnosis(self):

        return ', '.join([ disease.name for disease in self.diagnosis.all()[:3]])
    display_diagnosis.short_description = 'Diagnosis'
    

class PatientInstance(models.Model):

    card_number = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for a particular treatment case")
    patient = models.ForeignKey('Patient', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    discharge_time = models.DateField(null=True, blank=True)

    HEALTH_STATUS = (
        ('A', 'Admitted'),
        ('T', 'Treatment'),
        ('D', 'Discharge'),
    )

    status = models.CharField(max_length=1, choices=HEALTH_STATUS, blank=True, default='A', help_text="Patient Condition")

    class Meta:
        ordering = ['discharge_time']

    def __str__(self):

        return '{0} ({1})'.format(self.id,self.patient.firstname)

#model for devices in the clinic
class Device(models.Model):

    device_name = models.CharField(max_length=200)
    number_id = models.CharField(max_length=200)
    clinic_name = models.CharField(max_length=200)
    date_of_purchase = models.DateField('Purchase date', null=True, blank=True)

    class Meta:
        ordering = ["number_id","device_name"]

    def get_absolute_url(self):
        
        return reverse('device-detail', args=[str(self.id)])

    def __str__(self):

        return '{0}, {1}'.format(self.number_id,self.device_name)

patientRecord/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required #django import support for login required

# Create your views here.

from .models import Patient, Device, PatientInstance, Diagnosis

@login_required #testing required login to access homepage
def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_patients=Patient.objects.all().count()
    num_instances=PatientInstance.objects.all().count()
    # Admitted patient (status = 'a')
    num_instances_admitted=PatientInstance.objects.filter(status__exact='A').count()
    num_devices=Device.objects.all().count()  # The 'all()' is implied by default.

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_patients':num_patients,'num_instances':num_instances,'num_instances_admitted':num_instances_admitted,'num_devices':num_devices, 'num_visits':num_visits},
    )

# view for patients
from django.views import generic

class PatientListView(generic.ListView):
    model = Patient

class PatientDetailView(generic.DetailView):
    model = Patient

class DeviceListView(generic.ListView):
    model = Device

class DeviceDetailView(generic.DetailView):
    model = Device

# create, update and delete realdrip device manager 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Device
from .models import Patient

class DeviceCreate(CreateView):
    model = Device
    fields = '__all__'
    initial={'date_of_purchase':'05/01/2018',}

class DeviceUpdate(UpdateView):
    model = Device
    fields = ['device_name','number_id','clinic_name','date_of_purchase']

class DeviceDelete(DeleteView):
    model = Device
    success_url = reverse_lazy('devices')

#class specifications for patient delete

class PatientCreate(CreateView):
    model = Patient
    fields = ['firstname','lastname','gender','date_of_birth','address','summary','ClinicID']
    initial={'date_of_birth':'05/01/2018',}

class PatientUpdate(UpdateView):
    model = Patient
    fields = ['firstname','lastname','gender','date_of_birth','address','summary','ClinicID','device','diagnosis']

class PatientDelete(DeleteView):
    model = Device
    success_url = reverse_lazy('patients')

patientRecord/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>RealDrip IV Management</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Add additional CSS in static file -->
  {% load static %}
  {% include 'material/includes/material_css.html' %}
  {% include 'material/includes/material_js.html' %}	
  <!-- START STYLING -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/materialadmin.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/libs/rickshaw/rickshaw.css' %}" />
  <link type="text/css" rel="stylesheet" href="{% static 'css/libs/morris/morris.core.css' %}" />
  <!--STOP STYLING -->
</head>

<body class="menubar-hoverable header-fixed ">
          <!-- BEGIN HEADER-->         
		<header id="header" >
			<div class="headerbar">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="headerbar-left">
					<ul class="header-nav header-nav-options">
						<li class="header-nav-brand" >
							<div class="brand-holder">
								<a href="{% url 'index' %}">
									<span class="text-lg text-bold text-primary">REALDRIP</span>
								</a>
							</div>
            </li>
						<li>
							<a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
								<i class="fa fa-bars"></i>
							</a>
						</li>
					</ul>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
	 			<div class="headerbar-right">


					<ul class="header-nav header-nav-options">
            {% if user.is_authenticated %}	
					<ul class="header-nav header-nav-profile">
						<li class="dropdown">
							<a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
								<img src="{% static 'img/logo.png' %}" alt="" />
								<span style="font-size:14px;" class="profile-info">
									{{ user.get_username }}
								</span>
							</a>
            </li><!--end .dropdown -->
            <li class="dropdown"><a href="{% url 'logout'%}?next={{request.path}}" ><span style="font-size:14px;" class="profile-info">Logout</span></a></li>  
            {% else %}
            <li class="dropdown">
							<a href="{% url 'login'%}?next={{request.path}}">
								<span style="font-size:14px;" class="profile-info">
									Login
								</span>
							</a>
            </li><!--end .dropdown -->
            {% endif %}
          </ul><!--end .header-nav-profile -->        
				</div><!--end #header-navbar-collapse -->
			</div>
		</header>
		<!-- END HEADER-->
          <div id="base">
          {% block content %}{% endblock %}
          <div>

          <!-- BEGIN JAVASCRIPT -->
<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/libs/jquery/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/libs/spin.js/spin.min.js' %}"></script>
<script src="{% static 'js/libs/autosize/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/libs/moment/moment.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.time.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.resize.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/libs/flot/curvedLines.js' %}"></script>
<script src="{% static 'js/libs/jquery-knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'js/libs/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'js/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>
<script src="{% static 'js/libs/d3/d3.min.js' %}"></script>
<script src="{% static 'js/libs/d3/d3.v3.js' %}"></script>
<script src="{% static 'js/libs/rickshaw/rickshaw.min.js' %}"></script>
<script src="{% static 'js/core/source/App.js' %}"></script>
<script src="{% static 'js/core/source/AppNavigation.js' %}"></script>
<script src="{% static 'js/core/source/AppOffcanvas.js' %}"></script>
<script src="{% static 'js/core/source/AppCard.js' %}"></script>
<script src="{% static 'js/core/source/AppForm.js' %}"></script>
<script src="{% static 'js/core/source/AppNavSearch.js' %}"></script>
<script src="{% static 'js/core/source/AppVendor.js' %}"></script>
<script src="{% static 'js/core/demo/Demo.js' %}"></script>
<script src="{% static 'js/core/demo/DemoDashboard.js' %}"></script>
<!-- END JAVASCRIPT -->
</body>
</html>

patientRecord/templates/footer.html
{% load static %}
<!-- BEGIN JAVASCRIPT -->
<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/libs/jquery/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/libs/spin.js/spin.min.js' %}"></script>
<script src="{% static 'js/libs/autosize/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/libs/moment/moment.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.time.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.resize.min.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'js/libs/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/libs/flot/curvedLines.js' %}"></script>
<script src="{% static 'js/libs/jquery-knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'js/libs/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'js/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>
<script src="{% static 'js/libs/d3/d3.min.js' %}"></script>
<script src="{% static 'js/libs/d3/d3.v3.js' %}"></script>
<script src="{% static 'js/libs/rickshaw/rickshaw.min.js' %}"></script>
<script src="{% static 'js/core/source/App.js' %}"></script>
<script src="{% static 'js/core/source/AppNavigation.js' %}"></script>
<script src="{% static 'js/core/source/AppOffcanvas.js' %}"></script>
<script src="{% static 'js/core/source/AppCard.js' %}"></script>
<script src="{% static 'js/core/source/AppForm.js' %}"></script>
<script src="{% static 'js/core/source/AppNavSearch.js' %}"></script>
<script src="{% static 'js/core/source/AppVendor.js' %}"></script>
<script src="{% static 'js/core/demo/Demo.js' %}"></script>
<script src="{% static 'js/core/demo/DemoDashboard.js' %}"></script>
<!-- END JAVASCRIPT -->

patientRecord/templates/patientRecord/device_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Device</h1>

<p>Are you sure you want to delete the device: {{ device }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

patientRecord/templates/patientRecord/patient_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Patient</h1>

<p>Are you sure you want to delete the Patient Details: {{ patient }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

patientRecord/templates/patientRecord/patient_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content">
  <!-- BEGIN PROFILE HEADER -->
  <section class="full-bleed">
    <div class="section-body style-default-dark force-padding text-shadow">
      <div class="img-backdrop" style="background-image: url({% static 'img/dashboard.jpg' %})"></div>
      <div class="overlay overlay-shade-top stick-top-left height-3"></div>
      <div class="row">
        <div class="col-md-3 col-xs-5">
          <img class="img-circle border-white border-xl img-responsive auto-width" src="{% static 'img/logo2.png' %}" alt="" />
          <h3>{{ patient.firstname }}<br/><small>{{ patient.lastname }}</small></h3>
        </div><!--end .col -->
        <div class="col-md-9 col-xs-7">
          <div style="margin-left:30px;" class="width-3 text-center pull-right">
            <strong class="text-xl">{{ patient.card_number }}</strong><br/>
            <span class="text-light opacity-75">Card Number</span>
          </div>
          <div style="margin-left:30px;" class="width-3 text-center pull-right">
            <strong class="text-xl">{{ patient.ClinicID }}</strong><br/>
            <span class="text-light opacity-75">Clinic ID</span>
          </div>
        </div><!--end .col -->
      </div><!--end .row -->
      <div class="overlay overlay-shade-bottom stick-bottom-left force-padding text-right">
        <a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Contact me"><i class="fa fa-envelope"></i></a>
        <a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Follow me"><i class="fa fa-twitter"></i></a>
        <a class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Personal info"><i class="fa fa-facebook"></i></a>
      </div>
    </div><!--end .section-body -->
  </section>
  <!-- END PROFILE HEADER  -->

  <section>
    <div class="section-body no-margin">
      <div class="row">
        <div class="col-md-8">
          <h2>Summary</h2>

          <!-- BEGIN ENTER MESSAGE -->
          <form class="form">
            <div class="card no-margin">
              <div class="card-body">
                <div class="form-group floating-label">
                  <textarea readonly name="status" id="status" class="form-control autosize" rows="1"></textarea>
                  <label style="font-size:18px;" for="status">{{ patient.summary }}</label>
                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </form>

          <!-- BEGIN ENTER MESSAGE -->

          <!-- BEGIN MESSAGE ACTIVITY -->
          <div class="tab-pane" id="activity">
            <ul class="timeline collapse-lg timeline-hairline">
              <li class="timeline-inverted">
                <div class="timeline-circ circ-xl style-primary"><i class="md md-event"></i></div>
                <div class="timeline-entry">
                  <div class="card style-default-light">
                    <div class="card-body small-padding">
                      <span class="text-medium">{% for diagnosis in patient.diagnosis.all %} {{ diagnosis }}{% if not forloop.last %}, {% endif %}{% endfor %}</span><br/>
                      <span class="opacity-50">
                        Diagnosis
                      </span>
                    </div>
                  </div>
                </div><!--end .timeline-entry -->
              </li>
              <li>
                <div class="timeline-circ circ-xl style-primary-dark"><i class="md md-access-time"></i></div>
                <div class="timeline-entry">
                  <div class="card style-default-light">
                    <div class="card-body small-padding">
                      <p>
                        <span class="text-medium">{{ patient.date_of_birth }}</span><br/>
                        <span class="opacity-50">
                          Age
                        </span>
                      </p>
                      
                    </div>
                  </div>
                </div><!--end .timeline-entry -->
              </li>
              <li>
                <div class="timeline-circ circ-xl style-primary"><i class="md md-location-on"></i></div>
                <div class="timeline-entry">
                  <div class="card style-default-light">
                    <div class="card-body small-padding">
                      <img class="img-circle img-responsive pull-left width-1" src="{% static 'logo2.png' %}" alt="" />
                      {% for drip in patient.patientinstance_set.all %}
                      <span class="text-medium">{% if drip.status != 'A' %} <span class="text-primary">Due to be Discharged:</span> {{drip.discharge_time}}</span> {% endif %}<br/>
                      <span class="opacity-50">
                      Drip ID <strong>{{drip.id}}</strong> 
                      </span>
                    </div>
                    <div class="card-body">
                      <p>Imprint:<em>{{drip.imprint}}</em></p>
                      {% endfor %}
                      <img class="img-responsive" src="{% static 'img/dashboard.jpg' %}" alt="" />
                    </div>
                  </div>
                </div><!--end .timeline-entry -->
              </li>
            </ul>
          </div><!--end #activity -->
        </div><!--end .col -->
        <!-- END MESSAGE ACTIVITY -->

        <!-- BEGIN PROFILE MENUBAR -->
        <div class="col-lg-offset-1 col-lg-3 col-md-4">
          <div class="card card-underline style-default-dark">
            <div class="card-head">
              <header class="opacity-75"><small>More Details</small></header>
              <div class="tools">
                <form class="navbar-search" role="search">
                  <div class="form-group">
                    <input type="text" class="form-control" name="friendSearch" placeholder="Enter your keyword">
                  </div>
                  <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                </form>
              </div><!--end .tools -->
            </div><!--end .card-head -->
            <div class="card-body no-padding">
              <ul class="list">
                <li class="tile">
                  <a class="tile-content ink-reaction" href="#2">
                    <div class="tile-icon">
                      <img src="{% static 'img/logo2.png' %}" alt="" />
                    </div>
                    <div class="tile-text">{{ patient.device }}<small>Device</small></div>
                  </a>
                </li>
                <li class="tile">
                  <a class="tile-content ink-reaction">
                    <div class="tile-text">{{ patient.gender }}<small>Gender</small></div>
                  </a>
                </li>
                <li class="tile">
                  <a class="tile-content ink-reaction">
                    
                    <div class="tile-text">{{ patient.discharge_time }}<small>Discharge Time</small></div>
                  </a>
                </li>
                <li class="tile">
                  <a class="tile-content ink-reaction">
                    
                    <div class="tile-text">{{ drip.status }}<small>Patient Status</small></div>
                  </a>
                </li>
              </ul>
            </div><!--end .card-body -->
          </div><!--end .card -->
          <div class="card card-underline style-default-dark">
            <div class="card-head">
              <header class="opacity-75"><small>Personal info</small></header>
              <div class="tools">
                <a class="btn btn-icon-toggle ink-reaction"><i class="md md-edit"></i></a>
              </div><!--end .tools -->
            </div><!--end .card-head -->
            <div class="card-body no-padding">
              <ul class="list">
                <li class="tile">
                  <a class="tile-content ink-reaction">
                    <div class="tile-icon">
                      <i class="md md-location-on"></i>
                    </div>
                    <div class="tile-text">
                      {{ patient.address }}
                      <small>{{ patient.address }}</small>
                    </div>
                  </a>
                </li>
          
                <li class="divider-inset"></li>
                <li class="tile">
                  <a class="tile-content ink-reaction">
                    <div class="tile-icon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <div class="tile-text">
                      (234) 80 6353 7984
                      <small>Mobile</small>
                    </div>
                  </a>
                </li>
              </ul>
            </div><!--end .card-body -->
          </div><!--end .card -->
        </div><!--end .col -->
        <!-- END PROFILE MENUBAR -->

      </div><!--end .row -->
    </div><!--end .section-body -->
  </section>
  </div>

   <!--Menu set up -->
          <!-- BEGIN MENUBAR-->
          <div id="menubar" class="menubar-inverse ">
            <div class="menubar-fixed-panel">
              <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                  <i class="fa fa-bars"></i>
                </a>
              </div>
              <div class="expanded">
                <a href="{% url 'index' %}">
                  <span class="text-lg text-bold text-primary ">REALDRIP</span>
                </a>
              </div>
            </div>
            <div class="menubar-scroll-panel">
    
              <!-- BEGIN MAIN MENU -->
              <ul id="main-menu" class="gui-controls">
    
                <!-- BEGIN DASHBOARD -->
                <li>
                  <a href="{% url 'index' %}" class="active">
                    <div class="gui-icon"><i class="md md-home"></i></div>
                    <span class="title">Dashboard</span>
                  </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->
    
                <!-- BEGIN PATIENT -->
                <li class="gui-folder">
                  <a>
                    <div class="gui-icon"><i class="fa fa-puzzle-piece fa-fw"></i></div>
                    <span class="title">Patients</span>
                  </a>
                  <!--start submenu -->
                  <ul>
                    <li><a href="{% url 'patients' %}" ><span class="title">Patients List</span></a></li>
                    <li><a href="{% url 'patient_create' %}" ><span class="title">Register Patient</span></a></li>
                  </ul><!--end /submenu -->
                </li><!--end /menu-li -->
                <!-- END PATIENT -->
    
                <!-- BEGIN DEVICE -->
                <li class="gui-folder">
                  <a>
                    <div class="gui-icon"><i class="fa fa-table"></i></div>
                    <span class="title">Device</span>
                  </a>
                  <!--start submenu -->
                  <ul>
                    <li><a href="{% url 'devices' %}" ><span class="title">Device List</span></a></li>
                    <li><a href="{% url 'device_create' %}" ><span class="title">Register Device</span></a></li>
                  </ul><!--end /submenu -->
                </li><!--end /menu-li -->
                <!-- END DEVICE -->
    
                <!-- BEGIN USER -->
                <li class="gui-folder">
                  <a>
                    <div class="gui-icon"><span class="md md-account-box"></span></div>
                    <span class="title">{{ user.get_username }}</span>
                  </a>
                  <!--start submenu -->
                  <ul>
                    <li><a href="{% url 'password_change' %}" ><span class="title">Change Password</span></a></li>
                    <li><a href="{% url 'logout' %}" ><span class="title">Logout</span></a></li>
                    
                  </ul><!--end /submenu -->
                </li><!--end /menu-li -->
                <!-- END USER -->
    
                <!-- BEGIN SETTINGS -->
                <li>
                  <a href="" >
                    <div class="gui-icon"><i class="md md-settings-overscan"></i></div>
                    <span class="title">Settings</span>
                  </a>
                </li><!--end /menu-li -->
                <!-- END CHARTS -->
              </ul><!--end .main-menu -->
              <!-- END MAIN MENU -->
    
              <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                  <span class="opacity-75">Copyright &copy; 2018</span> <strong>RealDrip</strong>
                </small>
              </div>
            </div><!--end .menubar-scroll-panel-->
          </div><!--end #menubar-->
          <!-- END MENUBAR -->
{% endblock %}